server:
  port: 8080


spring:

  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: utf-8
    cache: false

  datasource:
    url:  jdbc:mysql://localhost:3306/kuhnsblog?characterEncoding=utf-8
    username :  root
    password :  admin
    driverClassName :  com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package : com.kuhn.kuhnsblog.model

#  spring.datasource.url = jdbc:mysql://localhost:3306/spring-security?characterEncoding=utf-8
#  spring.datasource.username = root
#  spring.datasource.password = admin
#  spring.datasource.driverClassName = com.mysql.jdbc.Driver



